========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  09:52:16 AM
Date is:  11-15-2020
Доброго дня
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/oleh/cautious-spoon/lab2
collected 4 items

tests/tests.py ..F.                                                      [100%]

=================================== FAILURES ===================================
___________________________ TestClass.test_home_work ___________________________

self = <tests.tests.TestClass testMethod=test_home_work>

    def test_home_work(self):
        # Ваш захист
>       self.assertTrue(home_work("http://date.jsontest.com/"))
E       AssertionError: None is not true

tests/tests.py:24: AssertionError
----------------------------- Captured stdout call -----------------------------
Доброго дня
=========================== short test summary info ============================
FAILED tests/tests.py::TestClass::test_home_work - AssertionError: None is no...
========================= 1 failed, 3 passed in 1.57s ==========================
